# name of the software
name: Kobalt Build Tool
# current version of the software
version: 0.811
# url of the download button
downloadUrl: https://github.com/cbeust/kobalt/releases
# licence of the software
license: Apache 2.0 License
licenseUrl: http://www.apache.org/licenses/

# list of additional links on the right of the top menu
headerLinks:
  - title: GitHub
    url: https://github.com/cbeust/kobalt

# list if additional links on the footer
footerLinks:
  - title: GitHub
    url: https://github.com/cbeust/kobalt-doc
  - title: Issues
    url: https://github.com/cbeust/kobalt-doc/issues?state=open

# header
header:
  color1: "#0047AB"
  color2: "#00275E"
  trianglify: true

# google analytics
analytics:
  account:
  domain:

# github buttons
githubButton:
  user: cbeust
  repo: kobalt

# twitter buttons
twitter:
  enabled: false
  via:
  hash:
  account:

# facebook buttons
facebook:
  enabled: false
  profileUrl:

exclude: ['README.md', 'LICENSE', 'bower.json', 'Gemfile.lock', 'Gemfile']

highlighter: pygments

gems:
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap